"""add new tables with constraints and validations

Revision ID: 162fb1280553
Revises: 4dc529621b1d
Create Date: 2026-03-20 11:35:14.936731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162fb1280553'
down_revision: Union[str, Sequence[str], None] = '4dc529621b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("email ~ '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='ck_user_email_format'),
    sa.CheckConstraint('LENGTH(password_hash) = 60', name='ck_user_password_hash_length'),
    sa.CheckConstraint('email = LOWER(email)', name='ck_user_email_lowercase'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('email_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider IN ('gmail', 'outlook')", name='ck_email_permission_provider_enum'),
    sa.CheckConstraint("scope IN ('read', 'read_and_train')", name='ck_email_permission_scope_enum'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('LENGTH(code) >= 8', name='ck_invite_code_length'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('training_data_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('ingested_by', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('ingested','removed')", name='ck_training_data_log_action_enum'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_logs_email_id'), 'training_data_logs', ['email_id'], unique=False)
    op.add_column('emails', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('emails', sa.Column('training_data_ingested', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'emails', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('emails', 'overridden_at')
    op.drop_column('emails', 'overridden_by')
    op.drop_column('emails', 'override_reason')
    op.drop_column('emails', 'manual_override')
    op.drop_column('emails', 'override_verdict')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('override_verdict', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('manual_override', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('override_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('overridden_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('overridden_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'training_data_ingested')
    op.drop_column('emails', 'created_by')
    op.drop_index(op.f('ix_training_data_logs_email_id'), table_name='training_data_logs')
    op.drop_table('training_data_logs')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_table('email_permissions')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
