"""Initial migration for Postgres

Revision ID: ca864f75f53b
Revises: 
Create Date: 2026-02-18 21:37:18.602851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca864f75f53b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=True),
    sa.Column('processed_emails', sa.Integer(), nullable=True),
    sa.Column('detector_accuracy', sa.Float(), nullable=True),
    sa.Column('generator_success_rate', sa.Float(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_round_status_enum'),
    sa.CheckConstraint('avg_confidence_score IS NULL OR (avg_confidence_score >= 0 AND avg_confidence_score <= 100)', name='ck_round_avg_confidence_range'),
    sa.CheckConstraint('detector_accuracy IS NULL OR (detector_accuracy >= 0 AND detector_accuracy <= 100)', name='ck_round_detector_accuracy_range'),
    sa.CheckConstraint('generator_success_rate IS NULL OR (generator_success_rate >= 0 AND generator_success_rate <= 100)', name='ck_round_generator_success_range'),
    sa.CheckConstraint('processed_emails <= total_emails', name='ck_round_processed_le_total'),
    sa.CheckConstraint('processed_emails >= 0', name='ck_round_processed_emails_nonneg'),
    sa.CheckConstraint('total_cost >= 0', name='ck_round_total_cost_nonneg'),
    sa.CheckConstraint('total_emails > 0', name='ck_round_total_emails_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("agent_type IN ('generator','detector','judge')", name='ck_api_agent_type_enum'),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_api_cost_nonneg'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ck_api_latency_nonneg'),
    sa.CheckConstraint('token_used IS NULL OR token_used >= 0', name='ck_api_token_used_nonneg'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_calls_round_id'), 'api_calls', ['round_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('generated_subject', sa.String(length=100), nullable=True),
    sa.Column('generated_body', sa.Text(), nullable=True),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('generated_email_metadata', sa.JSON(), nullable=False),
    sa.Column('generator_latency_ms', sa.Integer(), nullable=True),
    sa.Column('detector_verdict', sa.String(length=20), nullable=False),
    sa.Column('detector_risk_score', sa.Float(), nullable=True),
    sa.Column('detector_confidence', sa.Float(), nullable=True),
    sa.Column('detector_reasoning', sa.Text(), nullable=True),
    sa.Column('detector_latency_ms', sa.Integer(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=True),
    sa.Column('override_verdict', sa.String(length=20), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.String(length=100), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.CheckConstraint("detector_verdict IN ('phishing','legitimate')", name='ck_email_detector_verdict_enum'),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_email_cost_nonneg'),
    sa.CheckConstraint('detector_confidence >= 0 AND detector_confidence <= 1', name='ck_email_detector_confidence_range'),
    sa.CheckConstraint('detector_latency_ms IS NULL OR detector_latency_ms >= 0', name='ck_email_detector_latency_nonneg'),
    sa.CheckConstraint('generator_latency_ms IS NULL OR generator_latency_ms >= 0', name='ck_email_generator_latency_nonneg'),
    sa.CheckConstraint('processing_time IS NULL OR processing_time >= 0', name='ck_email_processing_time_nonneg'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_round_id'), 'emails', ['round_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('info','warning','error','critical')", name='ck_log_level_enum'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_round_id'), 'logs', ['round_id'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_table('manual_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('overridden_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("verdict IN ('correct','incorrect','phishing','legitimate')", name='ck_override_verdict_enum'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', name='uq_override_email_id')
    )
    op.create_index(op.f('ix_manual_overrides_email_id'), 'manual_overrides', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_overrides_email_id'), table_name='manual_overrides')
    op.drop_table('manual_overrides')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_round_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_emails_round_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_api_calls_round_id'), table_name='api_calls')
    op.drop_table('api_calls')
    op.drop_table('rounds')
    # ### end Alembic commands ###
