"""initial schema

Revision ID: f68964d2d980
Revises: 
Create Date: 2026-02-02 21:49:36.593993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68964d2d980'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_emails', sa.Integer(), nullable=True),
    sa.Column('processed_emails', sa.Integer(), nullable=True),
    sa.Column('detector_accuracy', sa.Float(), nullable=True),
    sa.Column('generator_success_rate', sa.Float(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('generated_subject', sa.String(length=100), nullable=True),
    sa.Column('generated_body', sa.Text(), nullable=True),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('generated_email_metadata', sa.JSON(), nullable=False),
    sa.Column('generator_latenc_ms', sa.Integer(), nullable=True),
    sa.Column('detector_verdict', sa.String(length=20), nullable=False),
    sa.Column('detector_risk_score', sa.Float(), nullable=True),
    sa.Column('detector_confidence', sa.Float(), nullable=True),
    sa.Column('detector_reasoning', sa.Text(), nullable=True),
    sa.Column('detector_latency_ms', sa.Integer(), nullable=True),
    sa.Column('judge_ground_truth', sa.String(length=20), nullable=False),
    sa.Column('is_judge_correct', sa.Boolean(), nullable=False),
    sa.Column('judge_quality_score', sa.Integer(), nullable=False),
    sa.Column('judge_verdict', sa.String(length=20), nullable=False),
    sa.Column('judge_reasoning', sa.Text(), nullable=True),
    sa.Column('judge_latency_ms', sa.Integer(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=True),
    sa.Column('override_verdict', sa.String(length=20), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.String(length=100), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['Rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Emails_round_id'), 'Emails', ['round_id'], unique=False)
    op.create_table('Logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['Rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Logs_level'), 'Logs', ['level'], unique=False)
    op.create_index(op.f('ix_Logs_round_id'), 'Logs', ['round_id'], unique=False)
    op.create_index(op.f('ix_Logs_timestamp'), 'Logs', ['timestamp'], unique=False)
    op.create_table('API_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_test_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=20), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_test_id'], ['Emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_API_calls_email_test_id'), 'API_calls', ['email_test_id'], unique=False)
    op.create_table('Manual_Overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_test_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('overridden_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_test_id'], ['Emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Manual_Overrides_email_test_id'), 'Manual_Overrides', ['email_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_Manual_Overrides_email_test_id'), table_name='Manual_Overrides')
    op.drop_table('Manual_Overrides')
    op.drop_index(op.f('ix_API_calls_email_test_id'), table_name='API_calls')
    op.drop_table('API_calls')
    op.drop_index(op.f('ix_Logs_timestamp'), table_name='Logs')
    op.drop_index(op.f('ix_Logs_round_id'), table_name='Logs')
    op.drop_index(op.f('ix_Logs_level'), table_name='Logs')
    op.drop_table('Logs')
    op.drop_index(op.f('ix_Emails_round_id'), table_name='Emails')
    op.drop_table('Emails')
    op.drop_table('Rounds')
